name: Action Gophers
description: 'Posts a gopher gif on every PR as a reward for pushing code.'
branding:
  icon: 'code'  
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'Github token for the repository'
    required: true
runs:
  using: docker
  image: Dockerfile